name: Prometheus Exporter for Postgres (pg14)

defaults:
  run:
    shell: bash
    working-directory: ./extensions/prometheus_exporter/

on:
  pull_request:
    branches:
      - main
    paths:
    - '.github/workflows/postgres_extension.yml'
    - 'extensions/prometheus_exporter/**'
  # Always run tests on main or release branches
  push:
    branches:
      - main
      - release**

jobs:
  test:
    name: Rust project
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "prometheus-exporter-test"
          workspaces: |
            extensions/prometheus_exporter

      - name: setup pgx
        run: cargo install --locked cargo-pgx

      - name: init
        run: cargo pgx init --pg14 download

      - name: test
        run: cargo test --no-default-features --features pg14
