name: Prometheus Exporter for Postgres (pg14)

defaults:
  run:
    shell: bash
    working-directory: ./extensions/prometheus_exporter/

on:
  pull_request:
    branches:
      - main
    paths:
    - '.github/workflows/postgres_extension.yml'
    - 'extensions/prometheus_exporter/**'
  # Always run tests on main or release branches
  push:
    branches:
      - main
      - release**

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "prometheus-exporter-lint"
          workspaces: |
            extensions/prometheus_exporter
          # Additional directories to cache
          cache-directories: |
            /home/runner/.pgx
      - name: setup pgx
        run: cargo install --locked cargo-pgx
      - name: init
        run: cargo pgx init --pg14 download
      - name: Cargo format
        run: cargo +nightly fmt --check
      - name: Clippy
        run: cargo clippy

  test:
    name: Rust project
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "prometheus-exporter-test"
          workspaces: |
            extensions/prometheus_exporter
          # Additional directories to cache
          cache-directories: |
            /home/runner/.pgx

      - name: setup pgx
        run: cargo install --locked cargo-pgx

      - name: init
        run: cargo pgx init --pg14 download

      - name: test
        run: cargo test --no-default-features --features pg14
