name: Prometheus Exporter for Postgres (pg14)

defaults:
  run:
    shell: bash
    working-directory: ./extensions/prometheus_exporter/

on:
  pull_request:
    branches:
      - main
    paths:
    - '.github/workflows/postgres_extension.yml'
    - 'extensions/prometheus_exporter/**'
  # Always run tests on main or release branches
  push:
    branches:
      - main
      - release**

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - uses: ./.github/actions/pgx-init
        with:
          working-directory: extensions/prometheus_exporter
      - name: Cargo format
        run: cargo +nightly fmt --check
      - name: Clippy
        run: cargo clippy

  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: ./.github/actions/pgx-init
        with:
          working-directory: extensions/prometheus_exporter
      - name: test
        run: cargo test --no-default-features --features pg14
