name: CoreDB operator tests

defaults:
  run:
    shell: bash
    working-directory: ./coredb-operator/

on:
  pull_request:
    branches:
      - main
    paths:
    - '.github/workflows/test_operator.yml'
    - 'coredb-operator/**'

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "coredb-operator-test"
          workspaces: |
            coredb-operator
      - name: Cargo test
        run: cargo test
  lint:
    name: Run linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "coredb-operator-lint"
          workspaces: |
            coredb-operator
      - uses: reinismu/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          working-directory: ./coredb-operator
