name: CoreDB operator tests

defaults:
  run:
    shell: bash
    working-directory: ./coredb-operator/

on:
  pull_request:
    branches:
      - main
    paths:
    - '.github/workflows/test_operator.yml'
    - 'coredb-operator/**'
  # Always run tests on main or release branches
  push:
    branches:
      - main
      - release**

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "coredb-operator-test"
          workspaces: |
            coredb-operator
      - name: Cargo test
        run: cargo test
  lint:
    name: Run linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "coredb-operator-lint"
          workspaces: |
            coredb-operator
      - name: Cargo format
        run: cargo +nightly fmt --check
      - name: Clippy
        run: cargo clippy
