name: CoreDB operator tests

defaults:
  run:
    shell: bash
    working-directory: ./coredb-operator/

on:
  pull_request:
    branches:
      - main
    paths:
    - '.github/workflows/test_operator.yml'
    - 'coredb-operator/**'

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo test
        run: cargo test
